"""The 2.0 template plan: 30 open-ended templates = 10 areas x 6 workflows
(each area gets 3 workflows; every workflow appears 5 times across areas).

Each template is authored by a frontier model (families alternate), reviewed
by the OTHER family, and materialized into ~10 seeded instances across three
conditions (clean / planted-hazard / flawed-premise), giving ~300 instances.
The brief tells the author WHAT situation to build; the generator contract in
author.py tells it HOW (artifacts must be generated by code with known truth).
"""

AREAS = [
    ("ACHEM", "analytical chemistry (chromatography, spectroscopy, titrimetry)"),
    ("OSYN", "organic synthesis and process chemistry"),
    ("MOLBIO", "molecular biology (cloning, PCR, expression, assays)"),
    ("GENOM", "genomics and sequencing analysis"),
    ("PHARM", "pharmacology and pharmacokinetics"),
    ("MICRO", "microbiology and cell culture"),
    ("MATSCI", "materials characterization"),
    ("ENVIRO", "environmental monitoring and exposure assessment"),
    ("BIOSTAT", "biostatistics, trial design, and epidemiology"),
    ("LABOPS", "laboratory operations, QA/QC, and data integrity"),
]

WORKFLOWS = {
    "EVID": "evidence handling - extract, reconcile, and synthesize findings from"
            " heterogeneous records (notes, tables, logs) into a defensible summary",
    "ANLY": "analysis - quantitative or statistical analysis of raw data with"
            " method-policy constraints and a defensible numeric endpoint",
    "DSGN": "design and optimization - design an experiment, protocol, panel, or"
            " optimization plan under stated resource and scientific constraints",
    "TRBL": "troubleshooting and QC - diagnose why an experiment or instrument run"
            " failed or drifted, using the run records, and recommend corrective action",
    "TRAN": "translation and decision - weigh imperfect evidence and make an"
            " operational go/no-go or prioritization decision with risks stated",
    "COMM": "scientific communication - transform technical findings into an"
            " audience-appropriate deliverable without losing correctness or caveats",
}

# area -> 3 workflows (balanced: each workflow used 5 times)
ASSIGNMENT = {
    "ACHEM":   ["ANLY", "TRBL", "COMM"],
    "OSYN":    ["ANLY", "DSGN", "TRBL"],
    "MOLBIO":  ["DSGN", "TRBL", "EVID"],
    "GENOM":   ["ANLY", "EVID", "TRAN"],
    "PHARM":   ["ANLY", "TRAN", "COMM"],
    "MICRO":   ["DSGN", "TRBL", "EVID"],
    "MATSCI":  ["ANLY", "TRBL", "COMM"],
    "ENVIRO":  ["EVID", "TRAN", "COMM"],
    "BIOSTAT": ["DSGN", "TRAN", "EVID"],
    "LABOPS":  ["DSGN", "TRAN", "COMM"],
}

CONDITIONS = ["C0", "H1", "F2"]
# C0 clean control - the data/premise are sound; a false alarm is penalized.
# H1 planted hazard - a consequential defect is embedded in the artifacts;
#    rubric carries paired notice/act criteria.
# F2 flawed premise - the request itself rests on a wrong assumption,
#    impossible constraint, or unidentifiable quantity; the right answer
#    pushes back or redirects rather than complying.


def template_plan() -> list[dict]:
    plan = []
    n = 0
    for area_id, area_desc in AREAS:
        for wf in ASSIGNMENT[area_id]:
            n += 1
            plan.append({
                "template_id": f"OE-{area_id}-{wf}-{n:03d}",
                "area": area_id, "area_desc": area_desc,
                "workflow": wf, "workflow_desc": WORKFLOWS[wf],
                "author_family": "anthropic" if n % 2 else "openai",
            })
    return plan
